ktor:
  application:
    modules:
      - com.jawa.ApplicationKt.module
  deployment:
    port: 8080
    host: 0.0.0.0
postgres:
  url: "jdbc:postgresql://localhost/$DATABASE_NAME"
  driver: "org.postgresql.Driver"
  username: "$USERNAME"
  password: "$PASSWORD"
